services:
  shfia-front:
    container_name: shfia-frontend
    build: .
    ports:
      - "5173:5173"  # Map host port 5173 to container port 5173
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    restart: unless-stopped

volumes:
  node_modules: